# Generated by Django 2.0.2 on 2018-05-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_geral', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='name',
        ),
    ]
