# Generated by Django 2.0.2 on 2018-05-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_geral', '0002_auto_20180507_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRecord',
            new_name='HistoricoAcessos',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
        migrations.RenameField(
            model_name='historicoacessos',
            old_name='date',
            new_name='dataAcesso',
        ),
        migrations.RenameField(
            model_name='historicoacessos',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nome',
        ),
    ]
